apiVersion: v1
kind: Service
metadata:
  name: employee-service
  labels:
    app: employee-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
  selector:
    app: employee-service

