apiVersion: apps/v1
kind: Deployment
metadata:
  name: candidate-service-deployment
  labels:
    app: candidate-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: candidate-service
  template:
    metadata:
      labels:
        app: candidate-service
    spec:
      containers:
        - name: candidate-service
          image: gcr.io/example-project-gke/candidate-service:v1.5
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgres:5432/candidatedb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
