apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: candidatedb
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: postgres-persistence-storage
      volumes:
        - name: postgres-persistence-storage
          persistentVolumeClaim:
            claimName: postgres-pvc-claim
