apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    tier: database
spec:
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
  selector:
    app: postgres
    tier: database

