apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
    tier: database
spec:
  ports:
  - port: 5432
    protocol: TCP
  type: ClusterIP
  selector:
    app: postgres
    tier: database

